version: '3'
services:
  krakend:
    image: devopsfaith/krakend
    ports:
      - 8080:8080
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    depends_on:
      - sp-positions-main-service
    networks:
      - emotico

  postgres:
    container_name: postgres
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - emotico

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - emotico

  sp-positions-main-service:
      container_name: sp-positions-main-service
      ports:
        - 9000:9000
      build:
        context: sp-positions-main-service
        dockerfile: build/Dockerfile
      restart: always
      networks:
        - emotico
      volumes:
        - ./configs/sp-positions-main-service/config.yaml:/app/config/config.yaml
  
  users-auth-service:
      container_name: users-auth-service
      ports:
        - 9001:9001
      build:
        context: users-auth-service
        dockerfile: build/Dockerfile
      restart: always
      networks:
        - emotico
      volumes:
        - ./configs/users-auth-service/config.yaml:/app/config/config.yaml


  sp-users-main-service:
      container_name: sp-users-main-service
      ports:
        - 9002:9002
      build:
        context: sp-users-main-service
        dockerfile: build/Dockerfile
      restart: always
      networks:
        - emotico
      volumes:
        - ./configs/sp-users-main-service/config.yaml:/app/config/config.yaml

  sp-interview-main-service:
      container_name: sp-interview-main-service
      ports:
        - 9003:9003
      build:
        context: sp-interview-main-service
        dockerfile: build/Dockerfile
      restart: always
      networks:
        - emotico
      volumes:
        - ./configs/sp-interview-main-service/config.yaml:/app/config/config.yaml
        - videos-vol:/app/videos
      
  sp-video-answer-analyzer:
      container_name: sp-video-answer-analyzer
      ports:
        - 9004:9004
      environment:
      - API_KEY=
      build:
        context: sp-video-answer-analyzer
        dockerfile: Dockerfile
      restart: always
      networks:
        - emotico
      volumes:
        - videos-vol:/app/videos
networks:
  emotico:
    driver: bridge

volumes:
  postgres-vol:
  positions-vol:
  videos-vol: