app:
  port: 9002
  timeout: 60s
db:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  db_name: users
  ssl_mode: disable
  timeout: 20s
redis:
  host: redis
  port: 6379
  db: 0
token:
  token_secret: superdupersecret
