app:
  port: 9001
  timeout: 60s
db:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  db_name: users
  ssl_mode: disable
  timeout: 20s
redis:
  host: redis
  port: 6379
  db: 0
token:
  access:
    token_secret: superdupersecret
    ttl: 9000s
    domain: localhost
  refresh:
    token_secret: superdupersecretofsecrets
    ttl: 86400s
    domain: localhost
