app:
  port: 9003
  timeout: 60s
db:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  db_name: users
  ssl_mode: disable
  timeout: 20s
video:
  path: /app/videos
  url: http://sp-video-answer-analyzer:9004
redis:
  host: localhost
  port: 6379
  db: 0
token:
  token_secret: superdupersecret
